version: "3.9"

services:
  backend:
    build: .
    dockerfile: Dockerfile.dev
    command: serve --http=0.0.0.0:8090
    volumes:
      - ./pb_data:/pb_data

  frontend:
    build: frontend
    ports:
      - 5173:5173
